# Exploración de datasets

## 0. Setup del proyecto

In [ ]:
import pandas as pd

ruta_inegi = "../data/raw/censo_inegi_2020.csv"

## 1. Dataset INEGI de Censo poblacional 2020

In [ ]:
#Cargamos el dataframe
df_inegi = pd.read_csv(ruta_inegi, dtype=str)

#Imprimimos tamaño para ver tamaño original
print(f"Tamaño original: {df_inegi.shape[0]} filas y {df_inegi.shape[1]} columnas.")

# Vemos las primeras 5 filas para entender la estructura
display(df_inegi.head())

Tamaño original: 71015 filas y 230 columnas.

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,AGEB,MZA,POBTOT,POBFEM,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC
0,26,Sonora,000,Total de la entidad Sonora,0000,Total de la entidad,0000,000,2944840,1472643,...,244972,811378,530511,501521,210780,126299,32807,48777,302080,11895
1,26,Sonora,001,Aconchi,0000,Total del municipio,0000,000,2563,1227,...,219,704,254,613,53,43,35,61,468,18
2,26,Sonora,001,Aconchi,0001,Total de la localidad urbana,0000,000,1650,785,...,189,473,193,394,42,34,19,32,290,10
3,26,Sonora,001,Aconchi,0001,Total AGEB urbana,0055,000,764,365,...,87,211,93,183,16,13,6,15,124,4
4,26,Sonora,001,Aconchi,0001,Aconchi,0055,001,0,0,...,0,0,0,0,0,0,0,0,0,0

### 1.1. Filtramos por la capital

In [10]:
# Filtramos usando la columna 'MUN' (Municipio)
# Usamos zfill(3) por si Pandas leyó un '30' en lugar de '030'
df_hmo = df_inegi[df_inegi['MUN'].str.zfill(3) == '030'].copy()

#Imprimimos tamaño para ver tamaño modificado
print(f"Tamaño Hermosillo: {df_hmo.shape[0]} filas y {df_hmo.shape[1]} columnas.")
df_hmo.head()

Tamaño Hermosillo: 17490 filas y 230 columnas.

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,AGEB,MZA,POBTOT,POBFEM,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC
26085,26,Sonora,030,Hermosillo,0000,Total del municipio,0000,000,936263,468773,...,94408,264173,195823,145475,92020,53512,8176,9791,69821,2328
26086,26,Sonora,030,Hermosillo,0001,Total de la localidad urbana,0000,000,855563,431621,...,93102,246615,189653,136543,90744,52642,6240,7586,57021,1509
26087,26,Sonora,030,Hermosillo,0001,Total AGEB urbana,0023,000,0,0,...,0,0,0,0,0,0,0,0,0,0
26088,26,Sonora,030,Hermosillo,0001,Hermosillo,0023,001,0,0,...,0,0,0,0,0,0,0,0,0,0
26089,26,Sonora,030,Hermosillo,0001,Hermosillo,0023,002,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df_hmo.info()

<class 'pandas.DataFrame'>
RangeIndex: 17490 entries, 26085 to 43574
Columns: 230 entries, ENTIDAD to VPH_SINTIC
dtypes: str(230)
memory usage: 30.7 MB

In [12]:
# Buscar columnas que contengan cierta palabra clave (ej. 'VIV' para viviendas)
palabra_clave = 'VIV'
columnas_encontradas = [col for col in df_hmo.columns if palabra_clave in col]

print(f"Columnas que contienen '{palabra_clave}':")
print(columnas_encontradas)

# Prueba cambiando la palabra clave a 'DREN' o 'INTER'

Columnas que contienen 'VIV':
['VIVTOT', 'TVIVHAB', 'TVIVPAR', 'VIVPAR_HAB', 'VIVPARH_CV', 'TVIVPARHAB', 'VIVPAR_DES', 'VIVPAR_UT', 'OCUPVIVPAR']